In [1]:
#import geopandas as gpd
import numpy as np
import pandas as pd
#import geopandas dataframe

In [2]:
df = pd.read_csv('speichern2.csv')

In [3]:
df

min_vv    max_vv   mean_vv  median_vv    std_vv     05_vv     25_vv  \
0      0.029655  0.059328  0.044970   0.046899  0.009040  0.032193  0.039151   
1      0.038104  0.071502  0.055315   0.054353  0.009468  0.041948  0.052576   
2      0.034223  0.054973  0.047080   0.050770  0.008278  0.034575  0.040628   
3      0.043288  0.090475  0.063751   0.063856  0.014111  0.045874  0.054512   
4      0.023024  0.046503  0.035872   0.035242  0.006792  0.026050  0.033723   
...         ...       ...       ...        ...       ...       ...       ...   
21224  0.054460  0.100460  0.087838   0.094188  0.015789  0.060601  0.084372   
21225  0.065006  0.099293  0.085376   0.090597  0.012253  0.066753  0.076681   
21226  0.081991  0.121187  0.100127   0.094899  0.014419  0.083593  0.088640   
21227  0.068409  0.100264  0.084457   0.083878  0.010896  0.069835  0.075882   
21228  0.069684  0.109504  0.088525   0.089265  0.014168  0.070200  0.077023   

          75_vv     95_vv    min_vh  ...   max_rvi  mean_rvi  median_rvi  \
0      0.050303  0.056813  0.006371  ...  1.231885  0.676656    0.600958   
1      0.059046  0.068714  0.004549  ...  0.738751  0.529685    0.534081   
2      0.054168  0.054741  0.008356  ...  1.035554  0.787898    0.786650   
3      0.069808  0.084659  0.009802  ...  0.862085  0.679501    0.646785   
4      0.039445  0.045019  0.004023  ...  1.139145  0.725447    0.693434   
...         ...       ...       ...  ...       ...       ...         ...   
21224  0.098506  0.100117  0.019543  ...  1.299713  0.938948    0.880552   
21225  0.094688  0.098906  0.011059  ...  1.076084  0.758615    0.809306   
21226  0.112766  0.120419  0.015042  ...  1.009296  0.788234    0.843463   
21227  0.093441  0.098261  0.017673  ...  1.021359  0.788931    0.716909   
21228  0.098589  0.108117  0.011621  ...  0.871676  0.653832    0.661432   

        std_rvi    05_rvi    25_rvi    75_rvi    95_rvi     Acquisition Time  \
0      0.258302  0.422554  0.536758  0.721173  1.111751  2020-08-23 12:53:42   
1      0.157914  0.302961  0.420416  0.660765  0.725187  2020-08-23 12:53:42   
2      0.150484  0.583732  0.699420  0.879700  0.994118  2020-08-23 12:53:42   
3      0.171063  0.442673  0.564667  0.859411  0.861974  2020-08-23 12:53:42   
4      0.196822  0.535375  0.576309  0.783538  1.050500  2020-08-23 12:53:42   
...         ...       ...       ...       ...       ...                  ...   
21224  0.224253  0.678572  0.781656  1.085685  1.278407  2019-09-28 23:17:24   
21225  0.208448  0.442282  0.646127  0.865894  1.021243  2019-09-28 23:17:24   
21226  0.165804  0.578170  0.626849  0.919048  0.997524  2019-09-28 23:17:24   
21227  0.134308  0.651166  0.675925  0.891592  0.984590  2019-09-28 23:17:24   
21228  0.132030  0.477459  0.555833  0.730654  0.839123  2019-09-28 23:17:24   

       Relative Height bin98 (cm)  
0                         3 - 6 m  
1                            <3 m  
2                            <3 m  
3                            <3 m  
4                         3 - 6 m  
...                           ...  
21224                    6 - 10 m  
21225                    6 - 10 m  
21226                     3 - 6 m  
21227                     3 - 6 m  
21228                        <3 m  

[21229 rows x 29 columns]

In [4]:
#df = df[(df['Acquisition Time'] >= '2020-01-01') & (df['Acquisition Time'] <= '2020-12-31')]
#np.unique(list(df['Acquisition Time']))

In [5]:
df = df.dropna()
df['Relative Height bin98 (cm)'].value_counts()

Relative Height bin98 (cm)
3 - 6 m     10177
<3 m         9163
6 - 10 m     1534
> 10 m        355
Name: count, dtype: int64

In [6]:
#for classification_report
#for confusion_matrix
#for accuracy_score
from sklearn import metrics as metrics

# for train_test_split
from sklearn import model_selection as model_selection

# For the classifier
from sklearn import ensemble as ensemble 
# for RandomForestClassifier

In [7]:
#cols = df.iloc[:,:-2]
#cols

In [8]:
'''
def loop_ada (cols):
    x = gdf[cols].values
    y = gdf["Relative Height bin98 (cm)"]
    x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size=0.2, random_state=1569)
    adaBoost_model = ensemble.AdaBoostClassifier(n_estimators=100, learning_rate=0.1)
    adaBoost_model.fit(x_train, y_train)
    adaBoost_prediction = adaBoost_model.predict(x_test)
    adaBoost_accuracy = metrics.accuracy_score(adaBoost_prediction, y_test)
    adaBoost_confusion_matrix = metrics.confusion_matrix(adaBoost_prediction, y_test)
    adaBoost_classification_report = metrics.classification_report(adaBoost_prediction, y_test)
    print("Accuracy:", adaBoost_accuracy)
'''

'\ndef loop_ada (cols):\n    x = gdf[cols].values\n    y = gdf["Relative Height bin98 (cm)"]\n    x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size=0.2, random_state=1569)\n    adaBoost_model = ensemble.AdaBoostClassifier(n_estimators=100, learning_rate=0.1)\n    adaBoost_model.fit(x_train, y_train)\n    adaBoost_prediction = adaBoost_model.predict(x_test)\n    adaBoost_accuracy = metrics.accuracy_score(adaBoost_prediction, y_test)\n    adaBoost_confusion_matrix = metrics.confusion_matrix(adaBoost_prediction, y_test)\n    adaBoost_classification_report = metrics.classification_report(adaBoost_prediction, y_test)\n    print("Accuracy:", adaBoost_accuracy)\n'

In [9]:
#from sklearn import preprocessing
#label_encoder = preprocessing.LabelEncoder()
#gdf["Relative Height bin98 (cm)"] = label_encoder.fit_transform(gdf["Relative Height bin98 (cm)"])
#gdf["Relative Height bin98 (cm)"].unique()

In [52]:
#x = gdf.iloc[:,4:-1].values
#x = df.iloc[:,:-2] #all features 0.58 alle Jahre split 0.2, 300, learning rate 1
#x = df.iloc[:,-11:-2].values
#x = df[['mean_vv','mean_vh','mean_rvi']] #acc. 0.57, split 0.2, 300, learning rate 1; alle Jahre: 0.587, rate 0.1, split 0.3: acc 0.60 aber klasse >10 raus; rate 10:
#x = df[['median_vv','median_vh','median_rvi']] #acc. 0.56 split 0.2, 300, learning rate 1
#x = df[['min_rvi','median_rvi','mean_rvi', '05_rvi', '25_rvi','75_rvi', '95_rvi']] #0.51
x = df[['min_rvi','max_rvi','min_vv', 'max_vv', 'min_vh','max_vh']] #0.59
#x = df[['std_vv', 'std_vh', 'std_rvi']]

# + scalar; 0.3, stratify, 300, rate 1:
#x = df.iloc[:,:-2] #0.57, SMOTE: 0.46
#x = df[['mean_vv','mean_vh','mean_rvi']] 0.59, ohne stratify + oversampling 0.48, Smote 0.47
y = df["Relative Height bin98 (cm)"]


'''
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import KBinsDiscretizer
rbX = RobustScaler()
x = rbX.fit_transform(x)

rbY = RobustScaler()
y = y.values.reshape(-1, 1)
#y = rbY.fit_transform(y)

n_bins = 4
# Initialize the discretizer
kbd = KBinsDiscretizer(n_bins=n_bins, encode='ordinal', strategy='quantile')

# Fit and transform 'y' into discrete bins
y = kbd.fit_transform(y)
'''
print(x)
print(y)

         std_vv    std_vh   std_rvi
0      0.009040  0.002239  0.258302
1      0.009468  0.002702  0.157914
2      0.008278  0.002091  0.150484
3      0.014111  0.004011  0.171063
4      0.006792  0.003197  0.196822
...         ...       ...       ...
21224  0.015789  0.005286  0.224253
21225  0.012253  0.005395  0.208448
21226  0.014419  0.004877  0.165804
21227  0.010896  0.002168  0.134308
21228  0.014168  0.005666  0.132030

[21229 rows x 3 columns]
0         3 - 6 m
1            <3 m
2            <3 m
3            <3 m
4         3 - 6 m
           ...   
21224    6 - 10 m
21225    6 - 10 m
21226     3 - 6 m
21227     3 - 6 m
21228        <3 m
Name: Relative Height bin98 (cm), Length: 21229, dtype: object


## Training and Test Samples

In [53]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size=0.3, random_state=0, stratify=y)
#x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size=0.3, random_state=0)

In [54]:
print(len(x_train), len(x_test), len(y_train), len(y_test))

14860 6369 14860 6369


In [55]:
# Versuch 1 Ungleichgewicht ausgleichen
#from imblearn.over_sampling import RandomOverSampler
#sampler = RandomOverSampler(sampling_strategy='not majority')
#x_resampled, y_resampled = sampler.fit_resample(x_train, y_train)

#Versuch 2 SMOTE
#from imblearn.over_sampling import SMOTE
#smote = SMOTE(sampling_strategy='auto')
#x_resampled, y_resampled = smote.fit_resample(x_train, y_train)


In [56]:
# Versuch mit Standard Scalar
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Anpassen des Scalers an die Trainingsdaten und Transformation von Trainingsdaten
x_train_scaled = scaler.fit_transform(x_train)

# oversampling:
#x_train_scaled = scaler.fit_transform(x_resampled)

# Transformation der Testdaten mit dem bereits angepassten Scaler
x_test_scaled = scaler.transform(x_test)

## Instantiation of the Model

In [57]:
#maybe add arguments
adaBoost_model = ensemble.AdaBoostClassifier(n_estimators=300, learning_rate=1)

## Fitting of the Classifiers

In [58]:
#adaBoost_model.fit(x_train, y_train)
adaBoost_model.fit(x_train_scaled, y_train)

#Oversampling
#adaBoost_model.fit(x_train_scaled, y_resampled)

AdaBoostClassifier(learning_rate=1, n_estimators=300)

In [59]:
#adaBoost_prediction = adaBoost_model.predict(x_test)
adaBoost_prediction = adaBoost_model.predict(x_test_scaled)

## Prediction of the Classifiers

In [60]:
'''
#adaBoost_prediction = adaBoost_model.predict(x_test)
rbY.fit(y_train)  # Fit the scaler on training data
adaBoost_prediction = rbY.inverse_transform(adaBoost_prediction.reshape(1, -1))
'''

'\n#adaBoost_prediction = adaBoost_model.predict(x_test)\nrbY.fit(y_train)  # Fit the scaler on training data\nadaBoost_prediction = rbY.inverse_transform(adaBoost_prediction.reshape(1, -1))\n'

In [61]:
np.unique(adaBoost_prediction, return_counts=True)

(array(['3 - 6 m', '6 - 10 m', '<3 m', '> 10 m'], dtype=object),
 array([4077,    8, 2282,    2]))

In [62]:
#adaBoost_prediction

In [63]:
np.unique(y_test, return_counts=True)

(array(['3 - 6 m', '6 - 10 m', '<3 m', '> 10 m'], dtype=object),
 array([3053,  460, 2749,  107]))

## Accuracy

In [64]:
adaBoost_accuracy = metrics.accuracy_score(adaBoost_prediction, y_test)
adaBoost_confusion_matrix = metrics.confusion_matrix(adaBoost_prediction, y_test)
adaBoost_classification_report = metrics.classification_report(adaBoost_prediction, y_test)

In [65]:
print("Accuracy:", adaBoost_accuracy)
print(adaBoost_confusion_matrix)
print(adaBoost_classification_report)

Accuracy: 0.568535091851154
[[2224  407 1352   94]
 [   5    2    1    0]
 [ 823   51 1395   13]
 [   1    0    1    0]]
              precision    recall  f1-score   support

     3 - 6 m       0.73      0.55      0.62      4077
    6 - 10 m       0.00      0.25      0.01         8
        <3 m       0.51      0.61      0.55      2282
      > 10 m       0.00      0.00      0.00         2

    accuracy                           0.57      6369
   macro avg       0.31      0.35      0.30      6369
weighted avg       0.65      0.57      0.60      6369

