## Applying machine learning technique (AdaBoost)

### Preparation

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read generated feature file
df = pd.read_csv('features_copy.csv') #umbenennen
df

min_vv    max_vv   mean_vv  median_vv    std_vv     05_vv     25_vv  \
0      0.029655  0.059328  0.044970   0.046899  0.009040  0.032193  0.039151   
1      0.038104  0.071502  0.055315   0.054353  0.009468  0.041948  0.052576   
2      0.034223  0.054973  0.047080   0.050770  0.008278  0.034575  0.040628   
3      0.043288  0.090475  0.063751   0.063856  0.014111  0.045874  0.054512   
4      0.023024  0.046503  0.035872   0.035242  0.006792  0.026050  0.033723   
...         ...       ...       ...        ...       ...       ...       ...   
21224  0.054460  0.100460  0.087838   0.094188  0.015789  0.060601  0.084372   
21225  0.065006  0.099293  0.085376   0.090597  0.012253  0.066753  0.076681   
21226  0.081991  0.121187  0.100127   0.094899  0.014419  0.083593  0.088640   
21227  0.068409  0.100264  0.084457   0.083878  0.010896  0.069835  0.075882   
21228  0.069684  0.109504  0.088525   0.089265  0.014168  0.070200  0.077023   

          75_vv     95_vv    min_vh  ...   max_rvi  mean_rvi  median_rvi  \
0      0.050303  0.056813  0.006371  ...  1.231885  0.676656    0.600958   
1      0.059046  0.068714  0.004549  ...  0.738751  0.529685    0.534081   
2      0.054168  0.054741  0.008356  ...  1.035554  0.787898    0.786650   
3      0.069808  0.084659  0.009802  ...  0.862085  0.679501    0.646785   
4      0.039445  0.045019  0.004023  ...  1.139145  0.725447    0.693434   
...         ...       ...       ...  ...       ...       ...         ...   
21224  0.098506  0.100117  0.019543  ...  1.299713  0.938948    0.880552   
21225  0.094688  0.098906  0.011059  ...  1.076084  0.758615    0.809306   
21226  0.112766  0.120419  0.015042  ...  1.009296  0.788234    0.843463   
21227  0.093441  0.098261  0.017673  ...  1.021359  0.788931    0.716909   
21228  0.098589  0.108117  0.011621  ...  0.871676  0.653832    0.661432   

        std_rvi    05_rvi    25_rvi    75_rvi    95_rvi     Acquisition Time  \
0      0.258302  0.422554  0.536758  0.721173  1.111751  2020-08-23 12:53:42   
1      0.157914  0.302961  0.420416  0.660765  0.725187  2020-08-23 12:53:42   
2      0.150484  0.583732  0.699420  0.879700  0.994118  2020-08-23 12:53:42   
3      0.171063  0.442673  0.564667  0.859411  0.861974  2020-08-23 12:53:42   
4      0.196822  0.535375  0.576309  0.783538  1.050500  2020-08-23 12:53:42   
...         ...       ...       ...       ...       ...                  ...   
21224  0.224253  0.678572  0.781656  1.085685  1.278407  2019-09-28 23:17:24   
21225  0.208448  0.442282  0.646127  0.865894  1.021243  2019-09-28 23:17:24   
21226  0.165804  0.578170  0.626849  0.919048  0.997524  2019-09-28 23:17:24   
21227  0.134308  0.651166  0.675925  0.891592  0.984590  2019-09-28 23:17:24   
21228  0.132030  0.477459  0.555833  0.730654  0.839123  2019-09-28 23:17:24   

       Relative Height bin98 (cm)  
0                         3 - 6 m  
1                            <3 m  
2                            <3 m  
3                            <3 m  
4                         3 - 6 m  
...                           ...  
21224                    6 - 10 m  
21225                    6 - 10 m  
21226                     3 - 6 m  
21227                     3 - 6 m  
21228                        <3 m  

[21229 rows x 29 columns]

In [3]:
# Using only one particular year (tested but with poorer results)
#df = df[(df['Acquisition Time'] >= '2020-01-01') & (df['Acquisition Time'] <= '2020-12-31')]
#np.unique(list(df['Acquisition Time']))

In [4]:
# Drop NAN-values and check data distribution
df = df.dropna()
df['Relative Height bin98 (cm)'].value_counts()

Relative Height bin98 (cm)
3 - 6 m     10177
<3 m         9163
6 - 10 m     1534
> 10 m        355
Name: count, dtype: int64

In [5]:
# for classification_report
# for confusion_matrix
# for accuracy_score
from sklearn import metrics as metrics

# for train_test_split
from sklearn import model_selection as model_selection

# for the classifier
from sklearn import ensemble as ensemble 
# for AdaBoostClassifier

In [6]:
# Choosing features and target value
# (Other feature combinations were tested but with poorer results)
x = df[['min_rvi','max_rvi','min_vv', 'max_vv', 'min_vh','max_vh']]
y = df["Relative Height bin98 (cm)"]
print(x)
print(y)

        min_rvi   max_rvi    min_vv    max_vv    min_vh    max_vh
0      0.387884  1.231885  0.029655  0.059328  0.006371  0.013197
1      0.272600  0.738751  0.038104  0.071502  0.004549  0.011534
2      0.534842  1.035554  0.034223  0.054973  0.008356  0.014888
3      0.399483  0.862085  0.043288  0.090475  0.009802  0.019520
4      0.525857  1.139145  0.023024  0.046503  0.004023  0.014033
...         ...       ...       ...       ...       ...       ...
21224  0.657690  1.299713  0.054460  0.100460  0.019543  0.036064
21225  0.400873  1.076084  0.065006  0.099293  0.011059  0.026067
21226  0.573085  1.009296  0.081991  0.121187  0.015042  0.030382
21227  0.649218  1.021359  0.068409  0.100264  0.017673  0.023457
21228  0.470740  0.871676  0.069684  0.109504  0.011621  0.030512

[21229 rows x 6 columns]
0         3 - 6 m
1            <3 m
2            <3 m
3            <3 m
4         3 - 6 m
           ...   
21224    6 - 10 m
21225    6 - 10 m
21226     3 - 6 m
21227     3 - 6 m
21

### Training and Test Samples

In [7]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size=0.3, random_state=0, stratify=y)

#x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size=0.3, random_state=0)

In [8]:
print(len(x_train), len(x_test), len(y_train), len(y_test))

14860 6369 14860 6369


In [9]:
# Address imbalanced data set

# Attempt 1: Oversampling
#from imblearn.over_sampling import RandomOverSampler
#sampler = RandomOverSampler(sampling_strategy='not majority')
#x_resampled, y_resampled = sampler.fit_resample(x_train, y_train)

# Attempt 2: SMOTE (Synthetic Minority Oversampling Technique)
#from imblearn.over_sampling import SMOTE
#smote = SMOTE(sampling_strategy='auto')
#x_resampled, y_resampled = smote.fit_resample(x_train, y_train)

In [10]:
# Standardization of dataset with Standard Scalar
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Adapting Scaler to test data and transform test data
x_train_scaled = scaler.fit_transform(x_train)

# Transformation of test data with already adapted Scaler
x_test_scaled = scaler.transform(x_test)

# Oversampling/Smote
#x_train_scaled = scaler.fit_transform(x_resampled)

### Instantiation of the Model

In [11]:
adaBoost_model = ensemble.AdaBoostClassifier(n_estimators=300, learning_rate=1)

### Fitting of the Classifiers

In [12]:
adaBoost_model.fit(x_train_scaled, y_train)

# Oversampling/SMOTE
#adaBoost_model.fit(x_train_scaled, y_resampled)

AdaBoostClassifier(learning_rate=1, n_estimators=300)

### Prediction of the Classifiers

In [13]:
adaBoost_prediction = adaBoost_model.predict(x_test_scaled)

In [14]:
# Check distribution of target test data
np.unique(y_test, return_counts=True)

(array(['3 - 6 m', '6 - 10 m', '<3 m', '> 10 m'], dtype=object),
 array([3053,  460, 2749,  107]))

### Accuracy

In [15]:
adaBoost_accuracy = metrics.accuracy_score(adaBoost_prediction, y_test)
adaBoost_confusion_matrix = metrics.confusion_matrix(adaBoost_prediction, y_test)
adaBoost_classification_report = metrics.classification_report(adaBoost_prediction, y_test)

In [16]:
print("Accuracy:", adaBoost_accuracy)
print(adaBoost_confusion_matrix)
print(adaBoost_classification_report)

Accuracy: 0.591301617208353
[[1843  366  865   86]
 [  46   43    2    5]
 [1147   46 1875   11]
 [  17    5    7    5]]
              precision    recall  f1-score   support

     3 - 6 m       0.60      0.58      0.59      3160
    6 - 10 m       0.09      0.45      0.15        96
        <3 m       0.68      0.61      0.64      3079
      > 10 m       0.05      0.15      0.07        34

    accuracy                           0.59      6369
   macro avg       0.36      0.45      0.37      6369
weighted avg       0.63      0.59      0.61      6369

