In [16]:
import geopandas as gpd
import numpy as np
#import geopandas dataframe

In [83]:
gdf = gpd.read_file('gdf_recl_lo_res.gpkg')

In [84]:
len(gdf.columns)

31

In [85]:
gdf = gdf[(gdf['Acquisition Time'] >= '2020-01-01') & (gdf['Acquisition Time'] <= '2020-12-31')]
np.unique(list(gdf['Acquisition Time']))

array([Timestamp('2020-06-01 07:57:08'), Timestamp('2020-06-05 06:22:39'),
       Timestamp('2020-06-09 04:48:05'), Timestamp('2020-07-15 04:33:58'),
       Timestamp('2020-07-19 02:59:06'), Timestamp('2020-07-23 01:24:13'),
       Timestamp('2020-07-26 23:49:22'), Timestamp('2020-07-30 22:15:01'),
       Timestamp('2020-08-03 20:41:34'), Timestamp('2020-08-06 05:58:37'),
       Timestamp('2020-08-07 19:08:04'), Timestamp('2020-08-10 04:25:04'),
       Timestamp('2020-08-11 17:34:29'), Timestamp('2020-08-15 16:00:55'),
       Timestamp('2020-08-18 01:17:56'), Timestamp('2020-08-19 14:27:20'),
       Timestamp('2020-08-21 23:44:19'), Timestamp('2020-08-23 12:53:42'),
       Timestamp('2020-08-25 22:10:40'), Timestamp('2020-08-27 11:20:02'),
       Timestamp('2020-09-02 19:03:15'), Timestamp('2020-09-06 17:29:28'),
       Timestamp('2020-09-10 15:55:43'), Timestamp('2020-09-12 05:05:24'),
       Timestamp('2020-09-14 14:22:53'), Timestamp('2020-09-20 01:59:48'),
       Timestamp('2020-09

In [86]:
gdf = gdf.dropna()
gdf['Relative Height bin98 (cm)'].value_counts()

Relative Height bin98 (cm)
3 - 6 m     40279
<3 m        21157
> 10 m      18980
6 - 10 m    15641
Name: count, dtype: int64

In [87]:
#gdf['05_vv'].corr(gdf['05_vh'])

In [88]:
#for classification_report
#for confusion_matrix
#for accuracy_score
from sklearn import metrics as metrics

# for train_test_split
from sklearn import model_selection as model_selection

# For the classifier
from sklearn import ensemble as ensemble 
# for RandomForestClassifier

In [89]:
cols = gdf.columns
cols = cols[4:-1]

In [90]:
#import pandas as pd
#import numpy as np
#df = pd.DataFrame(np.random.uniform(0,len(gdf),size=(len(gdf), 4)), columns=list('ABCD'))

In [91]:
def loop_ada (cols):
    x = gdf[cols].values
    y = gdf["Relative Height bin98 (cm)"]
    x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size=0.2, random_state=1569)
    adaBoost_model = ensemble.AdaBoostClassifier(n_estimators=100, learning_rate=0.1)
    adaBoost_model.fit(x_train, y_train)
    adaBoost_prediction = adaBoost_model.predict(x_test)
    adaBoost_accuracy = metrics.accuracy_score(adaBoost_prediction, y_test)
    adaBoost_confusion_matrix = metrics.confusion_matrix(adaBoost_prediction, y_test)
    adaBoost_classification_report = metrics.classification_report(adaBoost_prediction, y_test)
    print("Accuracy:", adaBoost_accuracy)

In [92]:
#for i in cols:
    #loop_ada([i])

In [125]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
gdf["Relative Height bin98 (cm)"] = label_encoder.fit_transform(gdf["Relative Height bin98 (cm)"])
gdf["Relative Height bin98 (cm)"].unique()

array([1, 0, 3, 2])

In [137]:
#x = gdf.iloc[:,4:-1].values
x = gdf[cols].values
#x = df.iloc[:,:].values

y = gdf["Relative Height bin98 (cm)"]



from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import KBinsDiscretizer
rbX = RobustScaler()
x = rbX.fit_transform(x)

rbY = RobustScaler()
y = y.values.reshape(-1, 1)
#y = rbY.fit_transform(y)

n_bins = 4
# Initialize the discretizer
kbd = KBinsDiscretizer(n_bins=n_bins, encode='ordinal', strategy='quantile')

# Fit and transform 'y' into discrete bins
y = kbd.fit_transform(y)
print(y)
print(x)

[[1.]
 [1.]
 [0.]
 ...
 [0.]
 [1.]
 [2.]]
[[  0.           0.96746433   0.64641462 ... -14.54313108   0.
   20.11117282]
 [  0.           0.96746433   0.64641462 ... -14.54313108   0.
   20.11117282]
 [  0.           0.96746433   0.64641462 ... -14.54313108   0.
   20.11117282]
 ...
 [  0.57076529   0.           0.         ...   1.           0.13307292
    0.        ]
 [  0.57076529   0.           0.         ...   1.           0.13307292
    0.        ]
 [  0.57076529   0.           0.         ...   1.           0.13307292
    0.        ]]


/home/ga59wig/micromamba/envs/geo419b_env/lib/python3.11/site-packages/sklearn/preprocessing/_discretization.py:322: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(


## Training and Test Samples

In [141]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size=0.5, random_state=1569)

In [142]:
print(len(x_train), len(x_test), len(y_train), len(y_test))

48028 48029 48028 48029


## Instantiation of the Model

In [143]:
#maybe add arguments
adaBoost_model = ensemble.AdaBoostClassifier(n_estimators=200, learning_rate=1)

## Fitting of the Classifiers

RobustScaler()

In [144]:
adaBoost_model.fit(x_train, y_train)

/home/ga59wig/micromamba/envs/geo419b_env/lib/python3.11/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(learning_rate=1, n_estimators=200)

In [145]:
adaBoost_prediction = adaBoost_model.predict(rbX.transform(x_test))

## Prediction of the Classifiers

array([[0., 0., 0., ..., 0., 0., 0.]])

In [154]:
#adaBoost_prediction = adaBoost_model.predict(x_test)
rbY.fit(y_train)  # Fit the scaler on training data
adaBoost_prediction = rbY.inverse_transform(adaBoost_prediction.reshape(1, -1))

In [159]:
adaBoost_prediction

array([[1., 1., 1., ..., 1., 1., 1.]])

## Accuracy

In [156]:
adaBoost_accuracy = metrics.accuracy_score(adaBoost_prediction, y_test)
adaBoost_confusion_matrix = metrics.confusion_matrix(adaBoost_prediction, y_test)
adaBoost_classification_report = metrics.classification_report(adaBoost_prediction, y_test)

ValueError: Found input variables with inconsistent numbers of samples: [1, 48029]

In [136]:
print("Accuracy:", adaBoost_accuracy)
print(adaBoost_confusion_matrix)
print(adaBoost_classification_report)

Accuracy: 0.4189968560661267
[[20124  7798 10527  9580]
 [    0     0     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       1.00      0.42      0.59     48029
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

    accuracy                           0.42     48029
   macro avg       0.25      0.10      0.15     48029
weighted avg       1.00      0.42      0.59     48029

